# 设置 AWS 配置参数
$AWS_ACCESS_KEY_ID="ASIAWLKYBGL5YRFP4EFJ"
$AWS_SECRET_ACCESS_KEY="leX6otESpzcFfp6AiDe6StdrlKdkOojMAwfuSxei"
$AWS_DEFAULT_REGION="us-east-1"
$AWS_SESSION_TOKEN="IQoJb3JpZ2luX2VjEEIaCXVzLXdlc3QtMiJHMEUCIAKqJLnWdNJIC2lpdVbUjfeiAlhlSuOKcbA3fiRxJRuRAiEAo/w79XG+e1NXf4XpCzlLC2pv8JXVRReNgK449GUi5LoqpAIIGxAAGgw0MzY2NjA2Nzk0MTkiDDpcX4b30ZqBjNwgmyqBAr91Q9QqtdBqMR3A7ceo2HjICreE3SgiMxVgWmBBChcps8+Nq2FJk7AD/JLZiUTeGImtUV9tnDq95xPdCNnAr++LazS0UrtwRvUiEncYGKXCxedQ/BcsXnLZE7LzoXHLmjeUvLZQmwmLZjJE1BLdmTlPQdn9QQ6d0eQ9Ebg9rSeb9xoV+9deYS3cexOOmPUNwkMAfTJA1nusxYGKTuw0vWASBgwS48VAOrNi5+Tz1LD0T8CK/wfCWNs32zrfXaTZy6ic0/cReTbyb1MgMhDLj1YFRwWITnIFtoMDUGvR4ptAKcxomaGNIPwDNZdTlGDED0py+S3zdoG5WK6OwuuVk58wMKWu5bQGOp0BUObYD+XKXaftswqGyBOgkAHYf5Rfy8CRAOSjEOCeOIe4fTqO1WrJ61N8IwRRs7nH9phMxZm7SKH+1c+K5611CzjYxWK87NcZ45KNeTGCudo2sZM4CsrR9xH9B9cxUzCVlSjBWz+hMzv7oUpFjMrCxkB+jA6xj1odKrbFIVJ70O2Izdi93jhgoQuFMzDeEamictYDyCcqleeQB95u+A=="
$ClusterName="MyEKS"

# 配置 AWS CLI
aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
aws configure set default.region $AWS_DEFAULT_REGION
aws configure set aws_session_token $AWS_SESSION_TOKEN

# 连接到 EKS 集群
aws eks --region us-east-1 update-kubeconfig --name $ClusterName

