apiVersion: storage.k8s.io/v1  # 指定Kubernetes API版本
kind: StorageClass  # 指定资源类型为StorageClass
metadata:
  name: efs-default  # StorageClass的名称
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  # 将此StorageClass标记为默认
provisioner: efs.csi.aws.com  # 指定动态卷供应器，这里是Amazon EFS CSI驱动
parameters:
  provisioningMode: efs-ap  # 指定供应模式为efs-ap，代表使用EFS Access Points
  fileSystemId: your-efs-id  # 指定EFS文件系统的ID
  directoryPerms: "777"  # 新创建的目录的权限设置
  gidRangeStart: "1000"  # GID范围的起始值，用于自动分配给新创建的目录
  gidRangeEnd: "2000"  # GID范围的结束值
  basePath: "/"  # 在EFS文件系统中为PV创建的基础路径