apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chat-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-chat-server
  template:
    metadata:
      labels:
        app: ai-chat-server
    spec:
      containers:
      - name: ai-chat-server
        image: 1098822169/ai-chat-server:latest
        ports:
        - containerPort: 5000