apiVersion: v1
kind: ConfigMap
metadata:
  name: config-volume
data:
  my.cnf: |
    [mysqld]
    user=mysql
    pid-file=/var/run/mysqld/mysqld.pid
    socket=/var/run/mysqld/mysqld.sock
    datadir=/var/lib/mysql
    symbolic-links=0
    bind-address=0.0.0.0
    default_authentication_plugin=mysql_native_password

    [mysqld_safe]
    log-error=/var/log/mysqld.log
    pid-file=/var/run/mysqld/mysqld.pid
