apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql/conf.d
        securityContext:
          runAsUser: 0  # 运行容器作为root用户
      volumes:  # 在这里添加对ConfigMap的引用
      - name: config-volume
        configMap:
          name: config-volume
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc