apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl-service
  template:
    metadata:
      labels:
        app: etl-service
    spec:
      containers:
      - name: etl-service
        image: your-docker-repo/etl-service:latest
        env:
        - name: DB_USER
          value: "your_db_user"
        - name: DB_PASSWORD
          value: "your_db_password"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        ports:
        - containerPort: 80
