apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31200
  type: NodePort
