minio:
  endpoint: http://3.237.17.173:32000
  access-key: minioadmin
  secret-key: minioadmin
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/k8sminio?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lrp123456
logging:
  level:
    com.byr: debug
  pattern:
    dateformat: HH:mm:ss
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
mybatis-plus:
  type-aliases-package: com.example.k8s_springboot.domain.po
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    map-underscore-to-camel-case: true # ?????????????
    cache-enabled: false # ????????
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      id-type: assign_id # id???????      update-strategy: not_null # ????????????
      update-strategy: not_null # ????????????
      logic-delete-field: deleted
knife4j:
  enable: true
  openapi:
    title: ????????
    description: "????????"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.example.k8s_springboot.controller


