apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32000  # 指定NodePort范围在30000-32767之间
  selector:
    app: minio
